name: 'octocheese'
description: 'Copy PyPI Packages to GitHub Releases'
author: 'Dominic Davis-Foster'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  pypi_name:
    description:
      The name of the project on PyPI.
    required: true
runs:
  using: composite
  steps:
  - name: Install octocheese and dependencies
    run: python3 -m pip install ${{ github.action_path }}/octocheese
    shell: bash
  - name: Run octocheese
    run: ${{ github.action_path }}/octocheese/octocheese/action.py
    shell: bash
